### ISSUE TITLE
Segmentation fault error with -P flag

### ISSUE THREAD

**Issue by tugceoruc** [Discngine/fpocket#105]
When I try to use -P flag I get the segmentation fault error.

I installed from conda via:
conda install -c conda-forge fpocket=4.1

To reproduce:
fpocket -f 6g2o.pdb -P 278:-:A.281:-:A.282:-:A

**Comment by oriondollar** [comment]
i'm having the same problem. would love some clarification on this.

**Comment by DAlvGar** [comment]
I came across the same problem and it took me a loooooong time to figure out and fix it: 

- modify line 50 of the `makefile` and instead of using `-std=c99` flag, use `-std=gnu99`

I am working on OpenSuse 15.5 and gcc 7.5.0. I hope it helps others! I am not sure how generic and back-compatible this is to change the repository code.

**Comment by pschmidtke** [comment]
oh, compilation crap probably, will add it to my list of things to do.

**Comment by pschmidtke** [comment]
Adressed & merged https://github.com/Discngine/fpocket/pull/117
