### ISSUE TITLE
Some questions about the software

### ISSUE THREAD

**Issue by CathalBio** [Discngine/fpocket#139]
I am using FPocket and have 3 questions main about how it works.
1. Is the algorithm stochastic or deterministic?
2. Can the pockets overlap? I am working with a protein where I know the active site position but I am using Fpocket to extract information (size, associated residues etc). On some of the proteins I run FPocket on there seems to be two ‘pocket’s’ within the same active site pocket. Are the simulated pockets able to overlap with one another?
3. Is there a list of what defines each of the outputs?

**Comment by pschmidtke** [comment]
- Is the algorithm stochastic or deterministic?
  - deterministic if you do not change anything on the input format
- Can the pockets overlap? I am working with a protein where I know the active site position but I am using Fpocket to extract information (size, associated residues etc). On some of the proteins I run FPocket on there seems to be two ‘pocket’s’ within the same active site pocket. Are the simulated pockets able to overlap with one another?
  - no, pockets are build from a clustering step of alpha spheres. An alpha sphere can only be part of a single cluster / pocket. You observe a larger binding site split into two pockets - different issue. 
- Is there a list of what defines each of the outputs?
  - Not sure I understand the question, otherwise the documentation here describes what is contained in which output file
