### ISSUE TITLE
No output from mdpocket on ubuntu 16.04

### ISSUE THREAD

**Issue by compchemeric** [Discngine/fpocket#15]
Hi,

i've been trying the whole day but i don't manage to get any output from mdpocket. I compiled fpocket with the tweak from the other thread "Make fails on Fedora 28" by out-commenting netcdf compilation in mdpocket.c and using the molfile libraries from VMD.

Running mdpocket without arguments gives the documentation as supposed to. Though, no matter what arguments i give, i always only get the documentation. No errors and no output, it only prints the documentation. It neither works with trajectory file nor with a list of pdb files. fpocket works perfectly fine.

Any idea what causes this? Where could i have gone wrong?

Best,
Eric

**Comment by pschmidtke** [comment]
could you please provide the command line you tried?


________________________________

**Comment by jldx** [comment]
Hi,

I have the same issue on Ubuntu 18.04 and Ubuntu 14.04 (personal and work computer)

I run `mdpocket --pdb_list mdpocket_input.txt --selected_pocket pocket7_atm.pdb` where:

* All files cited above are in the current directory from where I run the command
* mdpocket_input.txt provides the absolute path to the pdb obtained from `trjconv` command of Gromacs

I suspect an error in my command line but I can't figure it out.

Thank you!

Nb: In order to install the program without error, I had to comment lines 96-97 of mdpocket.c (issue #9). I don't think of it as the cause but it's worth mentioning it.

**Comment by jldx** [comment]
Hi @pschmidtke 

I have the same issue on Ubuntu 18.04 and Ubuntu 14.04 (personal and work computer)

I tried running those commands as suggested on SourceForge for the same issue without success: 
```
mdpocket --pdb_list mdpocket_input.txt --selected_pocket pocket7_atm.pdb
mdpocket -L mdpocket_input.txt
```
where:
* All files cited above are in the current directory from where I run the command
* `mdpocket_input.txt` provides the absolute path to the pdb obtained from `trjconv` command of Gromacs (obtained from you python script)

I suspect an error in my command lines but I can't figure it out.

Best,

Julie

Nb: In order to install the program without error, I had to comment lines 96-97 of mdpocket.c (issue #9). I don't think of it as the cause but it's worth mentioning it.

**Comment by pschmidtke** [comment]
1 : the command you run is the second step of mdpocket (analyzing a selected pocket. Did you run it already without the --selected_pocket argument?
What is in pocket7_atm.pdb?

Could you try to use the xtc file from gromacs directly? You should be able to do that on a presuperimposed trajectory.

Cheers

Peter

**Comment by CheyJones** [comment]
Hello,

I am also having issues with getting an output from MDpocket. I have tried running the 'mdpocket -L mdpocket_input.txt' command, as well as explicitly providing the DCD and topology files. Providing just the input list yields the documentation, whereas providing the explicit trajectory information leads to seg faults. Has this issue been resolved yet?

Thanks,
Chey
