### ISSUE TITLE
Running f-pocket on multiple protein structures

### ISSUE THREAD

**Issue by islem1994** [Discngine/fpocket#52]
Hello, 
I am a PhD student in Life and Health Sciences at Caen university.
In my project, I'm currently analysing a database where noble gases binding sites were modelled in all PDB entries, I'm looking for interesting proteins that bind noble gases, I'm trying to characterize those binding sites and calculate their volumes using f-pocket v 3.0 on linux.

When I run it on single proteins structures, it worked well. However, whenever I create a file that contains a list of PDB files, in order to run it on multiple protein structures I don't get any result.

I read the manual very carefully and I even checked similar answers to my question in 'The official support mailing list for fpocket' and I followed this example with this input:

110l.pdb
test_pdb4li2.pdb

Then I run f-pocket like this:

 ` ls -1 *.pdb > fpocketList.txt`
 ` fpocket -F fpocketList.txt`

I got this error message : 
  `! Invalid pdb name given.` 

Would you please help me to manager this error. In some cases, I need to analyse over than 100 proteins and I can't run f-pocket for each one separately.

I thank you in advance.

Best regards. 

_Islem HAMMAMI - PhD Student

GIP CYCERON - Unité ISTCT - Equipe CERVOxy
Bd H Becquerel 14074 Caen
www.istct.cyceron.fr

AIR LIQUIDE SANTE INTERNATIONAL
Paris Innovation Campus
1, chemin de la Porte des Loges
78350 Les loges en Josas - FRANCE
www.airliquide.com_

**Comment by harryjubb** [comment]
Hi Islem,

While I can't help you with the fPocket-specific issue, I can recommend running fPocket across a list of PDB files using GNU Parallel (https://www.gnu.org/software/parallel/).

You can construct a `parallel` command in which you can pipe in a list of files, and run fPocket on each. Roughly along the lines of (untested):

```parallel -j 0 fpocket -f < fpocketList.txt```

`parallel` will take advantage of multicore machines and can concurrently run as many fPocket calls as there are cores available.

As fPocket is very fast anyway, it shouldn't take long to run for ~100 proteins.

Alternatively, `xargs` can be used in a similar way, except it will take longer because it will run each PDB in serial.

**Comment by pschmidtke** [comment]
Nice. Can you put an example of that in the docs Harry? ;)
________________________________

**Comment by H-EKE** [comment]
Hi,

Are you aware where is it possilbe to run mdpocket in parallel? 


I was wondering if something like this would make sense 

```
parallel -j 0 ~/programs/fpocket/bin/mpocket --pdb_list List_prod1.txt

```
