### ISSUE TITLE
issues to compile the code with macOS Big Sur 11.1

### ISSUE THREAD

**Issue by rrako14** [Discngine/fpocket#58]
Hello, 

I am new to Mac and tried to compile the fpocket code with macOS Big Sur 11.1. I updated Xcode and MacPorts, and run the command lines as it is in the page with git and make. However, whenever I do this command: make ARCH=MACOSXX86_64, I got these messages: 

1 error generated.
make[1]: *** [obj/descriptors.o] Error 1
make: *** [all] Error 2

Not sure what are the issues, I have couples of warnings as well, please help!

**Comment by pschmidtke** [comment]
That should be fixed with the branch I just merged. There were yet again changes on the compilers permissivity on how ugly the makefile and circular dependencies can be :) 
I cannot test on big sur myself, but the azure pipelines should do that and I saw a similar error. 

Please let me know if that works on your end with the latest commit.

**Comment by rrako14** [comment]
Thank you! I am now able to compile the code and fpocket is working perfectly!
