### ISSUE TITLE
Why are the default parameters different from those published in the paper?

### ISSUE THREAD

**Issue by qyuan7** [Discngine/fpocket#62]
Hello fpocket team,

When I run fpocket from the Git repo, I found that some of the default parameters are different from those published in the paper, for example the default minimum and maximum radius values of the alpha sphere are 3.4 and 6.2 Å in the current implementation, while those values were 3.0 and 6.0 as published in the paper. Is there any specific reason for making such changes?

Thanks very much,

Best wishes.

Qi

**Comment by pschmidtke** [comment]
Hi, since the updates after fpocket 2.0 the clustering algorithm and default parameters changed indeed and a lot of parameters were adapted, also for the druggability estimations.

Hope that helps.

peter

________________________________
From: Qi Yuan ***@***.***>
Sent: Wednesday, April 21, 2021 21:26
To: Discngine/fpocket ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Discngine/fpocket] Why are the default parameters different from those published in the paper? (#62)


Hello fpocket team,

When I run fpocket from the Git repo, I found that some of the default parameters are different from those published in the paper, for example the default minimum and maximum radius values of the alpha sphere are 3.4 and 6.2 Å in the current implementation, while those values were 3.0 and 6.0 as published in the paper. Is there any specific reason for making such changes?

Thanks very much,

Best wishes.

Qi
