### ISSUE TITLE
Problems compiling with M1 chip Mac

### ISSUE THREAD

**Issue by SianXiaoCHN** [Discngine/fpocket#69]
Things happen to me like issue #58. I'm new to Mac and just used Mac with M1 chip.
I downloaded Xcode and command line tool, installed MacPorts. After I did this: make ARCH=MACOSXX86_64, I got error like this:

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/fpocket] Error 1

Is it related to M1 chip or other things, my group member used fpocket on Mac successfully, with Intel Mac before.

**Comment by pschmidtke** [comment]
Hi, 
I don't have any access to a mac with an M1 chip, so cannot really test. 
Did you already try the fpocket docker version instead?

As fpocket is depending now no the vmd molfile plugin, support from vmd for this architecture must be available prior to integrating that into fpocket.

**Comment by pschmidtke** [comment]
If you can compile the vmd plugin sources of the molfile plugin of the latest VMD version on your mac, then send over the corresponding so files so I can add them to the distribution. 

If you want to give the compilation a try here's an article on how to do that: 
https://www.discngine.com/blog/2019/5/25/building-the-vmd-molfile-plugin-from-source-code

You'd need to change the target architecture from MACOSXX86_64 to MACOSXARM64.

Right now I simply can't produce them without possessing a M1 chip myself. Otherwise it'll have to wait for github actions on M1 to be available.

**Comment by pschmidtke** [comment]
the plugin code (slightly adapted from the original code) is available on this repo:
https://github.com/Discngine/molfile_plugin

**Comment by sunhwan** [comment]
I have followed the guide and compiled the molfile plugin and moved the resulting shared/static library files to `plugins/MACOSXARM64/molfile` folder and I was able to compile fpocket using `make ARCH=MACOSXARM64` command. Thanks!

**Comment by SianXiaoCHN** [comment]
I remember the time I started the issue conda installation failed so I tried to complie. Now I just tried to use conda on both Mac M1 and CentOS, they both succeeded. Great job for solving all and giving the instruction on compilation.
