### ISSUE TITLE
mdpocket druggability scores

### ISSUE THREAD

**Issue by das22** [Discngine/fpocket#8]
Hi

I"m running mdpocket 3.0 with "mdpocket --trajectory_file md_skip_10.xtc --trajectory_format xtc -f ../solv_ions.pdb -S" however no apparent information on pocket druggability is generated in any of the output files. Should the "-S" flag not enable this?

A.

**Comment by pschmidtke** [comment]
sorry for the delay in the reply, it's holiday seaon in France ;) 
mdpocket can be run in two different ways, the first way, they way you ran it, to detect pockets all over the protein surface and calculate how often they occur and where. By default (without the -S) flag, these pocket frequency maps would show up all over the place ranging from 0 to 1,  1 being there all the time, 0 not at all. Note that these values can fluctuate a lot due to protein movement. 

When adding the -S flag, rather than writing the pure frequency of pocket appearance from 0 to 1, you actually ponderate this by the druggability score of the pocket at each frame on the location you are looking at; 

You'll end up with frequency grids with less pockets to analyze. If you find pockets with isovalues > 0.3 or 0.4 then you might have an interasting candidate.

Hope that helps. I'll try to make that more clear in the CLI and help.


As a side note, the second way of running mdpocket (as described in the pdf manual available in the repo), you can specify a pocket to select (with a supplementary pdb input file). When you do that, then you can calculate descriptors for your pocket, but not druggability...as the druggability score was trained on automatically detected pockets, and not a user defined area. However you have access to all descriptors composing the druggability score, like mean_local_hydrophobic density which is one of the main drivers. You can analyze that for instance.

Peter

**Comment by aishwaryshivgan** [comment]
Hello, I am running mdpocket the second way with selected pocket. I wanted to calculate draggability scores for each of the frames in the trajectory. I was looking though the paper but could not find exact equation to calculate the score. Do I take the linear combination of all the descriptors in the table 3 of https://pubs.acs.org/doi/abs/10.1021/jm100574m?
