### ISSUE TITLE
Why is fpocket not rotationally invariant?

### ISSUE THREAD

**Issue by Finnem** [Discngine/fpocket#81]
Hi,
When looking at the description of the fpocket algorithm it seems rotationally invariant to me, only based on sphere positions and distances between atoms. However, I tried applying fpocket to differently oriented versions of 4AGL and found that for some orientations, the found pockets can deviate significantly:
![grafik](https://user-images.githubusercontent.com/15279480/161534428-e5a56d48-9e85-4dd2-9e12-c20de2260c9e.png)

 So I was wondering at which step this difference is introduced. Could it be due to Qhull?

Thank you for your time :)

**Comment by pschmidtke** [comment]
Yes it's due to qhull and also the imprecision in the PDB coordinates and the subsequent clustering based on these results. These makes qhull quite sensitive to this. This effect has been a bit reduced with a "new" qvoronoi version but is still not 100% perfect yet. 
We tried several approaches to mitigate that but without success or with significant computational overhead.

**Comment by Finnem** [comment]
Thank you for your answer 👍
